ALTER TABLE TBL_CashAdvance ALTER COLUMN RecommendByID VARCHAR(30) NOT NULL;
ALTER TABLE TBL_CashAdvance ALTER COLUMN ApprovedByID  VARCHAR(30) NULL;
ALTER TABLE TBL_CashAdvance ALTER COLUMN CreatedBy     VARCHAR(30) NOT NULL;
ALTER TABLE TBL_CashAdvance ALTER COLUMN ModifiedBy    VARCHAR(30) NULL;
ALTER TABLE TBL_CashAdvance ALTER COLUMN EmployeeID VARCHAR(30) NOT NULL;